hiragana_app/config/routes.rb
Rails.application.routes.draw do
  resources :translations

  root 'translations#index'
end

hiragana_app/app/models/translation.rb
class Translation < ActiveRecord::Base
	belongs_to :word

end

hiragana_app/app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :translation

	def self.wordlist
	   YAML.load_file("docs/wordlist.yml").to_a
	end

end

hiragana_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hiragana_app/app/controllers/translations_controller.rb
class TranslationsController < ApplicationController

	def index
	end

	def show
		@word = Word.wordlist
		@translation = Translation.find(params[:id])
	end

	def new
		@word = Word.wordlist
		@translation = Translation.new
	end

	def create
		@translation = Translation.new(translation_params)
		
		if @translation.save
		redirect_to @translation
		else
		render 'new'
		end
 	end

 	private
 	def translation_params
 		params.require(:translation).permit(:text)
 	end

end

hiragana_app/app/helpers/application_helper.rb
module ApplicationHelper
end

hiragana_app/app/helpers/translations_helper.rb
module TranslationsHelper
end

hiragana_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hiragana</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container padd-top">
	<div class="jumbotron">

<%= yield %>
	
	</div>
</div>
</body>
</html>

hiragana_app/app/views/translations/create.html.erb
<p>(Create)</p>

hiragana_app/app/views/translations/index.html.erb
<p>(Index)</p>
<h1>Hello! こんにちは!</h1>
<p>Do you want to practice your hiragana? Let's start!</p>
<%= button_to "Start", new_translation_path, :class => "btn btn-primary btn-lg", :method => :get  %>



hiragana_app/app/views/translations/new.html.erb
<p>(New)</p>

<h1><%=@word[0][1]%></h1>

<%= form_for :translation, url: translations_path do |f| %>
<p><%= f.text_field :text %></p>
<p><%= f.submit %></p>
<% end %>

hiragana_app/app/views/translations/show.html.erb
<p>(Show)</p>

<h1><%= @word[0][0]%></h1>
<h1><%= @translation.text %></h1>

	<% if @translation.text == @word[0][1]%>
<p>Well done!</p>
	<%else%>
<p>You made a little mistake. It was: <%= @word[0][1]%></p>
	<%end%>
	